Use become syntax instead sudo
meAmidos/ansible-install-docker pull request #6
Opened 2017-02-16 12:28 UTC by t2d

Superseeded since ansilbe 1.9

2017-02-17 21:34 UTC, meAmidos commented
Thank you for the update.

It appears that the commit has some changes not related to the PR. Could you please clean it up?

2017-02-17 21:35 UTC, meAmidos requested changes

2017-02-17 21:35 UTC, meAmidos commented on tasks/main.yml
> +
The code related to the HTTP proxy probably does not belong here.

2017-02-18 11:09 UTC, t2d commented
You're right. I missed that. I cleaned it up.

2017-02-20 23:38 UTC, meAmidos approved these changes

2017-02-20 23:38 UTC, merged